### PR TITLE
NestedScrollView support

### PR DESCRIPTION
**Pull request by bhargavms**

### CODE REVIEW

**Comment by bhargavms** [comment]
Resolves issue #13

**Comment by bhargavms** [comment]
Credits @denisroyz

**Comment by musicdotexe** [comment]
It doesn't work in my case, brother. 
I can't wonder why onTouch event of NestedScrollView isn't fired in OverScrollBounceEffectDecoratorBase. Btw, overscrollmode in NestedScrollView is always assign into OVER_SCROLL_NEVER.

**Comment by varuntribe** [comment]
Please, can we get this merged?

**Pull request closed without merging**
